### PR TITLE
Fix container api (fix #800)

### LINKED ISSUE #800: Make "openio create" followed by "openio locate" work as expected
```
### 0 /home/jfs/public_git/github.com/jfsmig/oio-sds
(oio)jfs@jfs-lenovo 14 # openio container create JFS
+------+---------+
| Name | Created |
+------+---------+
| JFS  | True    |
+------+---------+


### 0 /home/jfs/public_git/github.com/jfsmig/oio-sds
(oio)jfs@jfs-lenovo 15 # openio --debug -v container locate JFS
Starting new HTTP connection (1): 127.0.0.1
"GET /v3.0/OPENIO/container/show?acct=ACCT&ref=JFS HTTP/1.1" 200 17
Starting new HTTP connection (1): 127.0.0.1
"GET /v3.0/OPENIO/reference/show?acct=ACCT&ref=JFS HTTP/1.1" 200 194
'system'
Traceback (most recent call last):
  File "/home/jfs/.local/python/oio/local/lib/python2.7/site-packages/cliff/app.py", line 387, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/jfs/.local/python/oio/local/lib/python2.7/site-packages/cliff/display.py", line 100, in run
    column_names, data = self.take_action(parsed_args)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/cli/storage/container.py", line 361, in take_action
    info = {'account': data['system']['sys.account'],
KeyError: 'system'
Exception raised: 'system'
```

### PR DESCRIPTION
**Pull request by fvennetier**

### CODE REVIEW

File: proxy/m2_actions.c [hunk 1]
```diff
@@ -317,18 +317,27 @@ _dump_json_prefixes (GString *gstr, GTree *tree_prefixes)
...
-		gboolean first = TRUE;
-		gboolean _func (gpointer k, gpointer v, gpointer i) {
-			(void) i;
-			COMA(gstr,first);
-			oio_str_gstring_append_json_pair (gstr, (const char *)k, (const char *)v);
-			return FALSE;
+	gboolean first = TRUE;
+	gboolean _func (gpointer k, gpointer v, gpointer i) {
+		gboolean system = GPOINTER_TO_INT(i);
+		if (system ^ g_str_has_prefix((gchar*)k, "user.")) {
```
Comment (jfsmig) [inline proxy/m2_actions.c]: I like this trick but it is hard to understand at a glance.
I suggest to make it a bit clearer, e.g. with a side-variable that will also make the subsequent `if (!system)` check clearer.
```
gboolean want_system = GPOINTER_TO_INT(i);
gboolean is_user = g_str_has_prefix((gchar*)k, "user.");
if (want_system ^ is_user) {
    if (is_user) /* ... */
}
